### PR TITLE
Olen changes + Fixes + HACS update

### PR DESCRIPTION
**Pull request by lbouriez**

### CODE REVIEW

**Comment by ping-localhost** [comment]
These are some great changes. Could you merge this @RodBr

**Comment by lbouriez** [comment]
> These are some great changes. Could you merge this @RodBr 

@ping-localhost you can directly use my fork if you want, I think the creator is not very actif on GitHub recently.

**Comment by ping-localhost** [comment]
That is what I am doing right now @lbouriez. Just noticed that min/max intensity and another max is missing, will open a PR once I got my Mi Flora integration working properly.

**Comment by lbouriez** [comment]
Don't hesitate :)

**Comment by lbouriez** [comment]
> That is what I am doing right now @lbouriez. Just noticed that min/max intensity and another max is missing, will open a PR once I got my Mi Flora integration working properly.

If u need help to get it working don't hesitate !

**Comment by RodBr** [comment]
Thanks, all. Yes, please feel free to take over.  Moved house and have had a bunch of repairs to do before setting up HA again.

**Pull request merged**
